### ISSUE TITLE
doctr is failing with 401 Client Error

### ISSUE THREAD

**Issue by ocefpaf** [drdoctr/doctr#148]
I am not sure if I am doing something wrong because in theory I should have all the proper rights to this repo, but when I try to use `doctr configure I get:

```
What repo do you want to build the docs for (org/reponame, like 'drdoctr/doctr')? sea-mat/sea-mat
Traceback (most recent call last):
  File "/home/filipe/miniconda3/envs/DOCTR/bin/doctr", line 11, in <module>
    sys.exit(main())
  File "/home/filipe/miniconda3/envs/DOCTR/lib/python3.5/site-packages/doctr/__main__.py", line 270, in main
    return process_args(get_parser())
  File "/home/filipe/miniconda3/envs/DOCTR/lib/python3.5/site-packages/doctr/__main__.py", line 113, in process_args
    return args.func(args, parser)
  File "/home/filipe/miniconda3/envs/DOCTR/lib/python3.5/site-packages/doctr/__main__.py", line 185, in configure
    is_private = check_repo_exists(build_repo, service='github', **login_kwargs)
  File "/home/filipe/miniconda3/envs/DOCTR/lib/python3.5/site-packages/doctr/local.py", line 244, in check_repo_exists
    r.raise_for_status()
  File "/home/filipe/miniconda3/envs/DOCTR/lib/python3.5/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/sea-mat/sea-mat
```

cc @rsignell-usgs

**Comment by asmeurer** [comment]
It's failing even for `drdoctr/doctr`. 

```
doctrmaster=$python -m doctr configure
What is your GitHub username? asmeurer
Enter the GitHub password for asmeurer:
A two-factor authentication code is required: app
Authentication code: 680140
What repo do you want to build the docs for (org/reponame, like 'drdoctr/doctr')? drdoctr/doctr
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/aaronmeurer/Documents/doctr/doctr/__main__.py", line 278, in <module>
    sys.exit(main())
  File "/Users/aaronmeurer/Documents/doctr/doctr/__main__.py", line 275, in main
    return process_args(get_parser())
  File "/Users/aaronmeurer/Documents/doctr/doctr/__main__.py", line 113, in process_args
    return args.func(args, parser)
  File "/Users/aaronmeurer/Documents/doctr/doctr/__main__.py", line 185, in configure
    is_private = check_repo_exists(build_repo, service='github', **login_kwargs)
  File "/Users/aaronmeurer/Documents/doctr/doctr/local.py", line 244, in check_repo_exists
    r.raise_for_status()
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/drdoctr/doctr
```

Something is messed up with the auth. It works if you do `--no-upload-key` (which you can use for now as a workaround).

**Comment by asmeurer** [comment]
Hmm. In the GitHub_login() function 401 means that it needs a 2-factor auth code. Are they not reusable for different requests anymore?

**Comment by asmeurer** [comment]
It looks like it is. So according to https://developer.github.com/v3/auth/#working-with-two-factor-authentication we need to create an access token (or else ask for the 2fa code every time we need it, but that would be very annoying).

**Comment by ocefpaf** [comment]
Thanks @asmeurer!

**Comment by asmeurer** [comment]
I just tested this again and it works. So maybe there was an upstream bug with GitHub that has been fixed.

**Comment by asmeurer** [comment]
Ah nope. Just saw it again.

**Comment by asmeurer** [comment]
It seems to be happening intermittently. I guess the 2fa code times out sometimes and sometimes it doesn't.

**Comment by asmeurer** [comment]
I think the code to manage tokens already exists for the private repo stuff. We may just need to refactor what's there.

**Comment by gforsyth** [comment]
I think it might've been an upstream issue? It seems to be working again on my end.

**Comment by asmeurer** [comment]
Do you have 2fa enabled on your account? Also note that the error was intermittent, so try it a few times.

**Comment by gforsyth** [comment]
I do and I tried it several times, also specifically waiting for the previous 2FA code to expire before continuing to the deploy key upload stage.

**Comment by asmeurer** [comment]
Maybe it is. I'll try it myself later.

**Comment by gforsyth** [comment]
Hey all, I'm going to close this out since it hasn't reared its head in a while.  I believe it was an upstream issue with GitHub. But please ping me on this issue if it shows up again.

**Comment by ocefpaf** [comment]
Sorry @gforsyth I forgot about this one.
