### ISSUE TITLE
SameFileError on build

### ISSUE THREAD

**Issue by choldgraf** [drdoctr/doctr#185]
I'm getting a strange error that I'm not sure how to debug. I'm trying to set up [this repo](https://github.com/choldgraf/zero_to_jupyterhub) with doctr but there seems to be some kind of error when it tries to move around the static files. Any idea what's up?

```
HEAD is now at 2e76101... fixing travis
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.0/bin/doctr", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/doctr/__main__.py", line 393, in main
    return process_args(get_parser(config=config))
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/doctr/__main__.py", line 211, in process_args
    return args.func(args, parser)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/doctr/__main__.py", line 264, in deploy
    dst=deploy_dir, log_file=log_file)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/doctr/travis.py", line 331, in sync_from_log
    shutil.copy2(f, new_f)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/shutil.py", line 98, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'build/html/_images/cloud_sdk_doc_landing.png' and 'build/html/_images/cloud_sdk_doc_landing.png' are the same file
```

**Comment by choldgraf** [comment]
Ah I realized that this was because I was misreading the docstring for the argument - I thought it was the *source* of the built HTML, not the *target* to where the HTML would be deployed. I think that the docs should be made more clear that it needs to be `doctr deploy <target-directory>` to avoid confusion.

**Comment by asmeurer** [comment]
I also just noticed that we have `doctr deploy` with no arguments in some places in our docs still.

**Comment by choldgraf** [comment]
yeah that's what threw me off
