### ISSUE TITLE
doctr fails with explicit _build/html

### ISSUE THREAD

**Issue by scopatz** [drdoctr/doctr#214]
I am seeing a same file copy error if I use the same dir as the default: https://travis-ci.org/ergs/website/builds/253744431#L1045

```
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/doctr", line 6, in <module>
    sys.exit(doctr.__main__.main())
  File "/home/travis/miniconda/lib/python3.6/site-packages/doctr/__main__.py", line 393, in main
    return process_args(get_parser(config=config))
  File "/home/travis/miniconda/lib/python3.6/site-packages/doctr/__main__.py", line 211, in process_args
    return args.func(args, parser)
  File "/home/travis/miniconda/lib/python3.6/site-packages/doctr/__main__.py", line 264, in deploy
    dst=deploy_dir, log_file=log_file)
  File "/home/travis/miniconda/lib/python3.6/site-packages/doctr/travis.py", line 331, in sync_from_log
    shutil.copy2(f, new_f)
  File "/home/travis/miniconda/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/travis/miniconda/lib/python3.6/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '_build/html/CNAME' and '_build/html/CNAME' are the same file
```

This goes away if I use the CWD `.`.  https://github.com/ergs/website/commit/28bf968d1a999358d96fd1b615dde7e012606cc6

This is hopefully a quick fix!

**Comment by asmeurer** [comment]
Should go away after the tempdir idea is implemented.
